# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180424_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='passwd',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
