# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='cpu_model',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hosts',
            name='disk_capacity',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
