# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20180424_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('passwd', models.CharField(max_length=32)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
