# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20180426_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='time',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
