# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('disk_num', models.CharField(max_length=32)),
                ('memory', models.CharField(max_length=32)),
                ('cpu', models.CharField(max_length=32)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Groups')),
            ],
        ),
    ]
