# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20180425_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cmd',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='hosts',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='passwd',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_group',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
