# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_hosts_v_or_s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_result',
            old_name='host_id',
            new_name='task_id',
        ),
    ]
