# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_task_result_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='cpu',
            field=models.CharField(max_length=32, verbose_name='cpu盒数'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='cpu_model',
            field=models.CharField(max_length=32, null=True, validators=['c', 'p', 'u', '型', '号']),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='disk_capacity',
            field=models.CharField(max_length=32, null=True, verbose_name='磁盘总大小'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='disk_num',
            field=models.CharField(max_length=32, verbose_name='磁盘数量'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Groups', verbose_name='主机id'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ip',
            field=models.CharField(max_length=32, verbose_name='主机ip'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='memory',
            field=models.CharField(max_length=32, verbose_name='内存大小'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='v_or_s',
            field=models.CharField(max_length=32, null=True, verbose_name='主机类型'),
        ),
    ]
