# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20180428_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='cpu_model',
            field=models.CharField(max_length=32, null=True, verbose_name='cpu型号'),
        ),
    ]
