# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20180428_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_status',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, verbose_name='系统账号名'),
        ),
    ]
