# Generated by Django 2.0.3 on 2018-05-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_control_group_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='proxy_or_client',
            field=models.CharField(max_length=32, null=True, verbose_name='服务器类型'),
        ),
    ]
